// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACmKT_jjwmCPRcqbG26Dz8k9vB1n5hwvE',
    appId: '1:569484291828:web:f25d849adfd347587ef8a1',
    messagingSenderId: '569484291828',
    projectId: 'chat-app-28dc4',
    authDomain: 'chat-app-28dc4.firebaseapp.com',
    storageBucket: 'chat-app-28dc4.firebasestorage.app',
    measurementId: 'G-BTK20GEC8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvmwJUOvpMpOCcjfYX-v7GoO6awzY78jk',
    appId: '1:569484291828:android:7c69dc9a95448c817ef8a1',
    messagingSenderId: '569484291828',
    projectId: 'chat-app-28dc4',
    storageBucket: 'chat-app-28dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwoT4skep7lT0NnJjcKBcB-EyzWRKgC7g',
    appId: '1:569484291828:ios:5b5f5a984aab76527ef8a1',
    messagingSenderId: '569484291828',
    projectId: 'chat-app-28dc4',
    storageBucket: 'chat-app-28dc4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwoT4skep7lT0NnJjcKBcB-EyzWRKgC7g',
    appId: '1:569484291828:ios:5b5f5a984aab76527ef8a1',
    messagingSenderId: '569484291828',
    projectId: 'chat-app-28dc4',
    storageBucket: 'chat-app-28dc4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACmKT_jjwmCPRcqbG26Dz8k9vB1n5hwvE',
    appId: '1:569484291828:web:a5c22f5481c23b4a7ef8a1',
    messagingSenderId: '569484291828',
    projectId: 'chat-app-28dc4',
    authDomain: 'chat-app-28dc4.firebaseapp.com',
    storageBucket: 'chat-app-28dc4.firebasestorage.app',
    measurementId: 'G-EPKFEK43N7',
  );
}
